FROM ruby:3.3-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      git \
      build-essential \
      libsqlite3-dev \
      libyaml-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["bundle", "exec", "rspec"]
